### ISSUE TITLE
Auth.py

### ISSUE THREAD

**Issue by clozinski** [Cromlech/CromlechCromDemo#2]
https://github.com/Cromlech/CromlechCromDemo/blob/master/src/cromdemo/src/cromdemo/auth.py

I think what you are trying to do here is start users  off wwith a very simple application. 
If so I should add some comments.  Here is simple ____.  For a more sophisticated e
traverser/auth/something_else see ................

logout makes sense, but why is it in the demo.  It should be part of the auth package. 

Rather than calling it class auth, you may want to call it class Application. 

I am quite surprised to see class secured. 

My take away is that I should now go and read cromlech.auth, 
cromlech.dawnlight.traverser, and whatever does a user database. cromlech.acl_folder?

Anyhow the important point is that it mostly all makes sense to me.  I have enough of an introduction from you to be able to find stuff on my own. 

Thank you. 

I am always happy to chat on IRC.

**Comment by trollfot** [comment]
Login/Logout is framework level, not toolkit level, since the login information can be anywhere.
Cromlech does not make this kind of decision for you, that's why it's in the app.

This is something you'll need to code each time because Cromlech is not a framework and not a CMS.
I agree that it's a lot of code, but it's what it is and it won't change, since session can be anything, login can be anything, the backend can be anything, the security model can be anything...
